name: express gcp stack
description: This stack sets up a express app and deploys it to GCP.
branding:
  icon: cloud
  color: blue

inputs:
  - name: workload_identity_provider
    type: string
    required: true
  - name: service_account
    type: string
    required: true
  - name: audience
    type: string
    required: true
  
init:
 uses: stack-init.yml
