name: express gcp stack test app and badge
description: This stack sets up a express app and deploys it to GCP.
branding:
  icon: cloud
  color: blue

inputs:
  - name: something
    type: string
    required: true

configs:
  repo-metadata:
    parameters:
      description: An express app on google app engine.
      topics:
        - nodejs
        - expressjs

  security:
    parameters:
      vulnerability-alerts: true
      automated-security-fixes: true

github-apps:
  - slug: stale

init:
 uses: stack-init.yml
