name: express setup
on: 
  workflow_dispatch:
   inputs:
    workload_identity_provider:
      required: true
    service_account:
      required: true
    audience:
      required: true
      
jobs:
  deploy-to-gcp:
    uses: octademo/deployment-workflows/.github/workflows/express_gcp_deploy.yml@main
    with:
      workload_identity_provider: ${{github.event.inputs.workload_identity_provider}}
      service_account: ${{github.event.inputs.service_account}}
      audience: ${{github.event.inputs.audience}}
